#!/bin/sh

dir="$(dirname $0)/../"
cd "$dir"
cmd="./firepath"

tmp=/tmp/$$

on_exit() {
    rm -f $tmp-*
    rm -f 'test/javascript/$path.js'
    rm -f 'test/typescript/$path.ts'
    rm -f 'test/java/Firepath.class'
    rm -f 'test/java/Test.class'
    rm -f 'test/java/Firepath.java'
}

trap "on_exit" EXIT

fail_msg() {
    echo "$cmd" 'NG: ' "$1"
}

fail_exit() {
    fail_msg "$1"
    exit 1
}

input_file='test/collection_structure.txt'

$cmd -l js -o 'test/javascript/$path.js' $input_file
[ $? -eq 0 ] || fail_exit "Fail to create javascript file"

$cmd -l ts -o 'test/typescript/$path.ts' $input_file
[ $? -eq 0 ] || fail_exit "Fail to create typescript file"

$cmd -l java -o 'test/java/Firepath.java' -a 'package=test.java' $input_file
[ $? -eq 0 ] || fail_exit "Fail to create java file"

cat <<EOF >$tmp-ans
/restaurant
/restaurant/restaurandId
/restaurant/restaurantId/reviews
/restaurant/restaurantId/reviews/reviewsId
/restaurant/restaurantId/orders
/restaurant/restaurantId/orders/ordersId
/restaurant/restaurantId/payments
/restaurant/restaurantId/payments/paymentsId
EOF

node test/javascript/test.js >$tmp-out
diff $tmp-ans $tmp-out
[ $? -eq 0 ] || fail_exit "javascript"

ts-node test/typescript/test.ts >$tmp-out
diff $tmp-ans $tmp-out
[ $? -eq 0 ] || fail_exit "typescript"

javac test/java/Test.java
java test.java.Test >$tmp-out
[ $? -eq 0 ] || fail_exit "java"
